### ISSUE TITLE
能否增加参数配置下拉刷新灵敏度？

### ISSUE THREAD

**Issue by liu-xinhui** [HzwSunshine/SRecyclerView#1]
现在的刷新总是要拖动很长距离才触发，能增加灵敏度调节就好了

**Comment by HzwSunshine** [comment]
可以的，需要继承AbsRefreshHeader重写getRefreshHeight()方法，然后设置想要的刷新触发距离，可以参考下Demo中的TestRefreshHeader类的写法

**Comment by HzwSunshine** [comment]
@liunewshine 可以的，需要继承AbsRefreshHeader重写getRefreshHeight()方法，然后设置想要的刷新触发距离，可以参考下Demo中的TestRefreshHeader类的写法

**Comment by HzwSunshine** [comment]
@liunewshine 1.2.8版本添加了支持灵敏度的调节，需要继承AbsRefreshHeader重写getRefreshSensitivity()方法，然后设置灵敏度，可以参考下Demo中的TestRefreshHeader类的写法
